name: Build and Release

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
            binary_name: img-velocity
          - os: macos-latest
            platform: macos
            arch: universal
            binary_name: img-velocity
          - os: windows-latest
            platform: windows
            arch: x86_64
            binary_name: img-velocity.exe

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Build binary
      run: |
        pyinstaller --onefile \
          --name img-velocity \
          --hidden-import PIL \
          --hidden-import PIL.Image \
          --hidden-import PIL.ImageFilter \
          --clean \
          img_velocity/main.py
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: img-velocity-${{ matrix.platform }}-${{ matrix.arch }}
        path: dist/${{ matrix.binary_name }}

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          img-velocity-linux-x86_64/img-velocity
          img-velocity-macos-universal/img-velocity
          img-velocity-windows-x86_64/img-velocity.exe
        draft: false
        prerelease: false