name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    
    - name: Format check with black
      run: |
        black --check img_velocity/
    
    - name: Lint with ruff
      run: |
        ruff check img_velocity/
    
    - name: Type check with mypy
      run: |
        mypy img_velocity/ --ignore-missing-imports
    
    - name: Security check with bandit
      run: |
        bandit -r img_velocity/ -ll

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Test minimum Python version on Linux
          - os: ubuntu-latest
            python-version: '3.9'
          # Test latest Python on all platforms
          - os: ubuntu-latest
            python-version: '3.13'
          - os: macos-latest
            python-version: '3.13'
          - os: windows-latest
            python-version: '3.13'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    
    - name: Run tests
      run: |
        pytest tests/ -v --cov=img_velocity --cov-report=xml --cov-report=term
    
    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check package
      run: |
        twine check dist/*
    
    - name: Test installation
      run: |
        pip install dist/*.whl
        img-velocity --help
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-packages
        path: dist/